---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages  
    package:
      name:
        - htop
        - vim-nox
        - tmux

  - name: Upgrade per apt-modul
    apt:
      upgrade: dist
        update_cache: yes
